import Header from './header/Header'
import Main from './main/Main'
import Card from './cards/Card'
import Desc from './desc/Desc'
import Showcase from './showcase/Showcase'
import Security from './security/Security'
import Work from './works/Work'
import Cta from './cta/Cta'
import Footer from './footer/Footer'
export { Header, Main, Card, Desc, Showcase, Security, Work, Cta, Footer }